package mokiyoki.enhancedanimals.init;

import mokiyoki.enhancedanimals.EnhancedAnimals;
import mokiyoki.enhancedanimals.items.*;
import mokiyoki.enhancedanimals.util.Reference;
import net.minecraft.item.Food;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.potion.EffectInstance;
import net.minecraft.potion.Effects;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.registries.ObjectHolder;

/**
 * Created by moki on 24/08/2018.
 */
@ObjectHolder(Reference.MODID)
public class ModItems {

    public static final Item Egg_White = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_white"));
    public static final Item Egg_CreamLight = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_creamlight"));
    public static final Item Egg_Cream = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cream"));
    public static final Item Egg_CreamDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_creamdark"));
    public static final Item Egg_CreamDarkest = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_creamdarkest"));  //carmel
    public static final Item Egg_CarmelDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_carmeldark"));
    public static final Item Egg_PinkLight = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinklight"));
    public static final Item Egg_Pink = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pink"));
    public static final Item Egg_PinkDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinkdark"));
    public static final Item Egg_PinkDarkest = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinkdarkest"));  //cherry
    public static final Item Egg_CherryDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cherrydark"));
    public static final Item Egg_BrownLight = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_brownlight"));
    public static final Item Egg_Brown = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_brown"));
    public static final Item Egg_BrownDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_browndark"));
    public static final Item Egg_Chocolate = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_chocolate"));
    public static final Item Egg_ChocolateDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_chocolatedark"));
    public static final Item Egg_Blue = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_blue"));
    public static final Item Egg_GreenLight = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(Reference.MODID, "egg_greenlight");
    public static final Item Egg_GreenYellow = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(Reference.MODID, "egg_greenyellow");
    public static final Item Egg_OliveLight = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_olivelight"));
    public static final Item Egg_Olive = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_olive"));
    public static final Item Egg_OliveDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_olivedark"));
    public static final Item Egg_BlueGrey = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_bluegrey"));
    public static final Item Egg_Grey = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_grey"));
    public static final Item Egg_GreyGreen = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_greygreen"));
    public static final Item Egg_Avocado = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_avocado"));
    public static final Item Egg_AvocadoDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_avocadodark"));
    public static final Item Egg_Mint = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_mint"));
    public static final Item Egg_Green = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_green"));
    public static final Item Egg_GreenDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_greendark"));
    public static final Item Egg_Pine = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pine"));
    public static final Item Egg_PineDark = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinedark"));

    public static final Item Egg_Cream_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cream_spot"));
    public static final Item Egg_CreamDark_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_creamdark_spot"));
    public static final Item Egg_Carmel_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_carmel_spot"));  //carmel
    public static final Item Egg_CarmelDark_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_carmeldark_spot"));
    public static final Item Egg_Pink_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pink_spot"));
    public static final Item Egg_PinkDark_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinkdark_spot"));
    public static final Item Egg_Cherry_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cherry_spot"));  //cherry
    public static final Item Egg_CherryDark_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cherrydark_spot"));
    public static final Item Egg_BrownLight_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_brownlight_spot"));
    public static final Item Egg_Brown_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_brown_spot"));
    public static final Item Egg_BrownDark_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_browndark_spot"));
    public static final Item Egg_Chocolate_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_chocolate_spot"));
    public static final Item Egg_GreenYellow_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(Reference.MODID, "egg_greenyellow");
    public static final Item Egg_Matcha_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_matcha_spot"));  //olivelight
    public static final Item Egg_Olive_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_olive_spot"));
    public static final Item Egg_OliveDark_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_olivedark_spot"));
    public static final Item Egg_Grey_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_grey_spot"));
    public static final Item Egg_GreyGreen_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_greygreen_spot"));
    public static final Item Egg_Avocado_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_avocado_spot"));
    public static final Item Egg_AvocadoDark_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_darkavocado_spot"));
    public static final Item Egg_Mint_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_mint_spot"));
    public static final Item Egg_Green_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_green_spot"));
    public static final Item Egg_GreenDark_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_greendark_spot"));
    public static final Item Egg_Pine_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pine_spot"));
    public static final Item Egg_PineDark_Spot = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinedark_spot"));

    public static final Item Egg_Cream_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cream_speckle"));
    public static final Item Egg_CreamDark_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_creamdark_speckle"));
    public static final Item Egg_Carmel_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_carmel_speckle"));  //carmel
    public static final Item Egg_CarmelDark_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_carmeldark_speckle"));
    public static final Item Egg_Pink_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pink_speckle"));
    public static final Item Egg_PinkDark_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinkdark_speckle"));
    public static final Item Egg_Cherry_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cherry_speckle"));  //cherry
    public static final Item Egg_CherryDark_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cherrydark_speckle"));
    public static final Item Egg_BrownLight_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_brownlight_speckle"));
    public static final Item Egg_Brown_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_brown_speckle"));
    public static final Item Egg_BrownDark_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_browndark_speckle"));
    public static final Item Egg_Chocolate_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_chocolate_speckle"));
    public static final Item Egg_GreenYellow_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(Reference.MODID, "egg_greenyellow");
    public static final Item Egg_Matcha_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_matcha_speckle"));  //olivelight
    public static final Item Egg_Olive_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_olive_speckle"));
    public static final Item Egg_OliveDark_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_olivedark_speckle"));
    public static final Item Egg_Grey_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_grey_speckle"));
    public static final Item Egg_GreyGreen_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_greygreen_speckle"));
    public static final Item Egg_Avocado_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_avocado_speckle"));
    public static final Item Egg_AvocadoDark_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_darkavocado_speckle"));
    public static final Item Egg_Mint_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_mint_speckle"));
    public static final Item Egg_Green_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_green_speckle"));
    public static final Item Egg_GreenDark_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_greendark_speckle"));
    public static final Item Egg_Pine_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pine_speckle"));
    public static final Item Egg_PineDark_Speckle = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinedark_speckle"));

    public static final Item Egg_Cream_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cream_spatter"));
    public static final Item Egg_CreamDark_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_creamdark_spatter"));
    public static final Item Egg_Carmel_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_carmel_spatter"));  //carmel
    public static final Item Egg_CarmelDark_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_carmeldark_spatter"));
    public static final Item Egg_Pink_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pink_spatter"));
    public static final Item Egg_PinkDark_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinkdark_spatter"));
    public static final Item Egg_Cherry_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cherry_spatter"));  //cherry
    public static final Item Egg_CherryDark_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_cherrydark_spatter"));
    public static final Item Egg_BrownLight_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_brownlight_spatter"));
    public static final Item Egg_Brown_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_brown_spatter"));
    public static final Item Egg_BrownDark_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_browndark_spatter"));
    public static final Item Egg_Chocolate_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_chocolate_spatter"));
    public static final Item Egg_GreenYellow_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(Reference.MODID, "egg_greenyellow");
    public static final Item Egg_Matcha_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_matcha_spatter"));  //olivelight
    public static final Item Egg_Olive_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_olive_spatter"));
    public static final Item Egg_OliveDark_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_olivedark_spatter"));
    public static final Item Egg_Grey_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_grey_spatter"));
    public static final Item Egg_GreyGreen_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_greygreen_spatter"));
    public static final Item Egg_Avocado_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_avocado_spatter"));
    public static final Item Egg_AvocadoDark_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_darkavocado_spatter"));
    public static final Item Egg_Mint_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_mint_spatter"));
    public static final Item Egg_Green_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_green_spatter"));
    public static final Item Egg_GreenDark_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_greendark_spatter"));
    public static final Item Egg_Pine_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pine_spatter"));
    public static final Item Egg_PineDark_Spatter = new EnhancedEgg(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(new ResourceLocation(Reference.MODID, "egg_pinedark_spatter"));

    public static final Item RawChicken_DarkSmall = new RawChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(1).saturation(2.2F).effect(new EffectInstance(Effects.HUNGER, 600, 0), 0.3F).meat().build())).setRegistryName(Reference.MODID, "rawchicken_darksmall");
    public static final Item RawChicken_Dark = new RawChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(1).saturation(2.2F).effect(new EffectInstance(Effects.HUNGER, 600, 0), 0.3F).meat().build())).setRegistryName(Reference.MODID, "rawchicken_dark");
    public static final Item RawChicken_DarkBig = new RawChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(2).saturation(2.2F).effect(new EffectInstance(Effects.HUNGER, 600, 0), 0.3F).meat().build())).setRegistryName(Reference.MODID, "rawchicken_darkbig");
    public static final Item RawChicken_PaleSmall = new RawChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(1).saturation(2.2F).effect(new EffectInstance(Effects.HUNGER, 600, 0), 0.3F).meat().build())).setRegistryName(Reference.MODID, "rawchicken_palesmall");
    public static final Item RawChicken_Pale = new RawChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(1).saturation(2.2F).effect(new EffectInstance(Effects.HUNGER, 600, 0), 0.3F).meat().build())).setRegistryName(Reference.MODID, "rawchicken_pale");
    public static final Item CookedChicken_DarkSmall = new CookedChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(2).saturation(7.2F).meat().build())).setRegistryName(Reference.MODID, "cookedchicken_darksmall");
    public static final Item CookedChicken_Dark = new CookedChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(4).saturation(7.2F).meat().build())).setRegistryName(Reference.MODID, "cookedchicken_dark");
    public static final Item CookedChicken_DarkBig = new CookedChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(6).saturation(7.2F).meat().build())).setRegistryName(Reference.MODID, "cookedchicken_darkbig");
    public static final Item CookedChicken_PaleSmall = new CookedChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(2).saturation(7.2F).meat().build())).setRegistryName(Reference.MODID, "cookedchicken_palesmall");
    public static final Item CookedChicken_Pale = new CookedChicken(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(4).saturation(7.2F).meat().build())).setRegistryName(Reference.MODID, "cookedchicken_pale");
    public static final Item RawRabbit_Small = new RawRabbit(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(1).saturation(1.8F).meat().build())).setRegistryName(Reference.MODID, "rawrabbit_small");
    public static final Item CookedRabbit_Small = new CookedRabbit(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(3).saturation(6F).meat().build())).setRegistryName(Reference.MODID, "cookedrabbit_small");
    public static final Item RabbitStew_Weak = new RabbitStew(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(64).food((new Food.Builder()).hunger(8).saturation(12F).meat().build())).setRegistryName(Reference.MODID, "rabbitstew_weak");

    public static final Item Half_Milk_Bottle = new MilkBottleHalf(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1).containerItem(Items.GLASS_BOTTLE).food((new Food.Builder()).setAlwaysEdible().hunger(0).saturation(0F).build())).setRegistryName(Reference.MODID, "half_milk_bottle");
    public static final Item Milk_Bottle = new MilkBottle(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1).containerItem(Items.GLASS_BOTTLE).food((new Food.Builder()).setAlwaysEdible().hunger(0).saturation(0F).build())).setRegistryName(Reference.MODID, "milk_bottle");
    public static final Item OneSixth_Milk_Bucket = new MilkBucketOneSixth(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1).containerItem(Items.BUCKET).food((new Food.Builder()).setAlwaysEdible().hunger(0).saturation(0F).build())).setRegistryName(Reference.MODID, "onesixth_milk_bucket");
    public static final Item OneThird_Milk_Bucket = new MilkBucketOneThird(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1).containerItem(Items.BUCKET).food((new Food.Builder()).setAlwaysEdible().hunger(0).saturation(0F).build())).setRegistryName(Reference.MODID, "onethird_milk_bucket");
    public static final Item Half_Milk_Bucket = new MilkBucketHalf(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1).containerItem(Items.BUCKET).food((new Food.Builder()).setAlwaysEdible().hunger(0).saturation(0F).build())).setRegistryName(Reference.MODID, "half_milk_bucket");
    public static final Item TwoThirds_Milk_Bucket = new MilkBucketTwoThirds(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1).containerItem(Items.BUCKET).food((new Food.Builder()).setAlwaysEdible().hunger(0).saturation(0F).build())).setRegistryName(Reference.MODID, "twothirds_milk_bucket");
    public static final Item FiveSixths_Milk_Bucket = new MilkBucketFiveSixths(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1).containerItem(Items.BUCKET).food((new Food.Builder()).setAlwaysEdible().hunger(0).saturation(0F).build())).setRegistryName(Reference.MODID, "fivesixths_milk_bucket");

    public static final Item Genetics_Encyclopedia = new GeneticsEncyclopedia(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(Reference.MODID, "genetics_encyclopedia");
    public static final Item Debug_Gene_Book = new DebugGenesBook(new Item.Properties().group(EnhancedAnimals.GENETICS_ANIMALS_GROUP).maxStackSize(1)).setRegistryName(Reference.MODID, "debug_gene_book");
}

