modLoader="javafml"
loaderVersion="[34,)"

license="All rights reserved"

[[mods]]
modId="eanimod"
version="0.8.36"
displayName="Genetic Animals"
logoFile="icon.png"
authors="Moki, BeardedDev, Nicole, Mika, Navia"
credits="Everyone on the Genetic Animals Patreon!"
description='''
Genetics with improved animal behaviour and extra animal content.
'''